// <auto-generated />
using GraphDesignApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphDesignApp.Migrations
{
    [DbContext(typeof(GraphicDesignContext))]
    partial class GraphicDesignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphDesignApp.GraphicDesign", b =>
                {
                    b.Property<int>("GraphicDesignId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<int>("DesignType");

                    b.Property<string>("EmailAddress");

                    b.Property<int>("PaperQuality");

                    b.Property<int>("ShippingType");

                    b.Property<int>("Size");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("GraphicDesignId")
                        .HasName("PK_GraphicDesigns");

                    b.HasIndex("EmailAddress");

                    b.ToTable("GraphicDesigns");
                });

            modelBuilder.Entity("GraphDesignApp.UserAccount", b =>
                {
                    b.Property<string>("EmailAddress")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("EmailAddress")
                        .HasName("PK_UserAccounts");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("GraphDesignApp.GraphicDesign", b =>
                {
                    b.HasOne("GraphDesignApp.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("EmailAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
